language: generic
services:
- docker
install:
- docker build -t bucharestgold/fedora-node . 
- docker run -it -v ${PWD}/rpms:/root/rpmbuild/RPMS bucharestgold/fedora-node
before_deploy:
- echo "Before deploy."
deploy:
  provider: releases
  api_key:
    secure: OeCuM7QWJFt2yH1dJ9KLky6W1XZXpxjYwnKcGBWBdvr+S3ysq4J+2E3UwnqBvLmpzekYMBzI4oTPmd6HxyiTat9Ha3XhZdfhvP1+bUjsYRsAUh2pqSxmQVk4D5u6W+4xs0QJxyZ8/FOUFf9PuD9kzSYTYCEgr0H9ZYWouKQL2sJtL+rRMtMJfin8suPGbpPjG12x1ljaXbawdH/yJL5LYBuYI67s9nj9iDVSVrNxTpwRmBfuSoADJPEUTr44Lgd0CxVJvxC7ort2MefxpIwgt0SriGeq+iBTN6Ksl/XnPl10rhMDpoKkyeyTdwJZ1/UBJA7N0bL0bgzfCDgAtwAp+GlwWKUzY73rAPcoJGVh8uvn+7MyJPQNNV8fG+d5DxoAzf2FK13S0jfiYyckYIqYZSxq0ydjQIOkhQoUXjfFcjJu7fv0gEETyZT7PTa/EEpOktR/N72g8cKFG6FDuLkI4OHKnsLuzW/px9xpYd9nxM0beVW0HdScG2p6iWkpSg9fMbp9AqrcnDpgafq/ifCSlhNBKjjpykly0896A+ynUsoanZdcU1q7gGF+9d4IEpL/zl7cOmiJJXSq9RO4jwg2aeeb+TuBXSEeLXkcs7aW1MHv2kfmxCXgciYZ+vv+qMVIKZhE1jCJ1kAy6kgGMwBOaMdpQJX9nWxmYDoJ2jxz4U4=
  file_glob: true
  file: rpms/**/*.rpm
  skip_clean: true
  on:
    tags: true
